name: Publish Python 🐍 distributions 📦 to PyPI
on:
  push:
    tags:        
      - 2*

jobs:
  publish:
    name: "Build, test and upload to pypi"
    runs-on: "ubuntu-latest"
    environment:
      name: pypi
      url: https://pypi.org/project/PyDriller/
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install dependencies and unzip test-repos
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install pytest-cov
          unzip test-repos
      - name: Mypy
        run: |
          pip install mypy
          mypy --ignore-missing-imports pydriller/ tests/
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Run pytest
        run: pytest tests/ --cov=pydriller/ --cov-report=xml
      - name: Build app
        run: |
          pip install wheel 
          python setup.py bdist_wheel
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
